# version: '3.8'
# Hoy en día la línea de versión es opcional, pero se recomienda incluirla para 
# garantizar la compatibilidad con las características específicas de esa versión de Docker Compose.

services:
  web_app:
    image: python:3.10-slim
    container_name: django-compose-env
    command: tail -f /dev/null
    ports:
      - "8000:8000"
    networks:
      - red_local

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M

  database:
    image: postgres:15-alpine
    container_name: postgres-compose-env
    environment:
      POSTGRES_DB: mi_base_django
      POSTGRES_PASSWORD: mi_pass_seguro
    networks:
      - red_local
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

networks:
  red_local:
    driver: bridge