apiVersion: apps/v1
kind: Deployment

metadata:
  name: mi-blog
  labels:
    app: blog

spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: nginx-blog
        image: nginx:alpine

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: checkout-pro
  labels:
    servicio: pagos

spec:
  replicas: 5
  selector: 
    matchLabels:
      servicio: pagos
  template:
    metadata:
      labels:
        servicio: pagos
    spec:
      containers:
      - name: pay-logic
        image: httpd:alpine

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: multi-tool
  labels:
    app: herramientas

spec:
  replicas: 2
  selector:
    matchLabels:
      app: herramientas
  template:
    metadata:
      labels:
        app: herramientas
    spec:
      containers:
      - name: principal
        image: nginx
      - name: ayudante
        image: redis:alpine