name: "Terraform CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-checks:
    name: "Validar Código de Terraform"
    runs-on: ubuntu-latest

    # Le dice a GitHub que ejecute todo dentro de tu carpeta específica
    defaults:
      run:
        working-directory: ./project2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      # Al inicializar para CI, no necesitamos descargar plugins reales del backend
      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate


  # Segundo job que depende del primero, se ejecutará solo si el primero pasa
  security-scan:
    name: "Security Scan"
    runs-on: ubuntu-latest

    # Aquí le decimos al segundo job que depende y necesita el primero para ejecutarse
    needs: terraform-checks

    env: 
      STAGE: "staging"

    steps:
      - name: Security Scan
        run: echo "Running security scan for ${STAGE} environment"

      - name: Authenticate Security Scanner
        run: echo "Authenticating with $MY_TOKEN"
        env:
          MY_TOKEN: ${{ secrets.API_SECURITY_TOKEN }}